/* 회원 */
DROP TABLE BOOK_MEMBER 
   CASCADE CONSTRAINTS;

/* 도서 */
DROP TABLE BOOK 
   CASCADE CONSTRAINTS;

/* 도서대출정보 */
DROP TABLE BOOK_DETAIL 
   CASCADE CONSTRAINTS;

/* 게시판 */
DROP TABLE BOOK_BOARD 
   CASCADE CONSTRAINTS;

/* 댓글 */
DROP TABLE BOOK_COMMENT 
   CASCADE CONSTRAINTS;

/* ban목록 */
DROP TABLE BOOK_BANLIST 
   CASCADE CONSTRAINTS;

/* 대출 */
DROP TABLE BOOK_LOAN 
   CASCADE CONSTRAINTS;

/* 회원신고 */
DROP TABLE MEMBER_DECLARE 
   CASCADE CONSTRAINTS;

/* 도서훼손정보 */
DROP TABLE BOOK_DAMAGE_DETAIL 
   CASCADE CONSTRAINTS;

/* 도서예약정보 */
DROP TABLE BOOK_RESERVATION 
   CASCADE CONSTRAINTS;

/* 회원 */
CREATE TABLE BOOK_MEMBER (
   MEMBER_SEQ NUMBER NOT NULL, /* 회원번호 */
   ID VARCHAR2(30) NOT NULL, /* 아이디 */
   PASSWORD VARCHAR2(20) NOT NULL, /* 비밀번호 */
   NAME VARCHAR2(20) NOT NULL, /* 이름 */
   NICKNAME VARCHAR2(20) NOT NULL, /* 닉네임 */
   PHONE VARCHAR2(20) NOT NULL, /* 전화번호 */
   AUTH CHAR(1) NOT NULL, /* 권한 */
   BANFLAG CHAR(1) NOT NULL, /* 정지여부 */
   DECLARE_COUNT NUMBER NOT NULL, /* 탈퇴여부 */
   MEMBER_DELFLAG CHAR(1) NOT NULL /* 신고누적횟수 */
);
INSERT INTO BOOK_MEMBER
(MEMBER_SEQ, ID, PASSWORD, NAME, NICKNAME, PHONE, AUTH, BANFLAG, DECLARE_COUNT, MEMBER_DELFLAG)
VALUES(0, 'asd', '1234', '강남호', '호랑이', '010', 'U', 'N', 0, 'N');



ALTER TABLE BOOK_MEMBER
   ADD
      CONSTRAINT PK_BOOK_MEMBER
      PRIMARY KEY (
         MEMBER_SEQ
      );

/* 도서 */
CREATE TABLE BOOK (
   BOOK_SEQ NUMBER NOT NULL, /* 도서번호 */
   THUMBNAIL VARCHAR2(100), /* 표지 */
   TITLE VARCHAR2(50) NOT NULL, /* 제목 */
   AUTHORS VARCHAR2(50), /* 저자리스트 */
   PUBLISHER VARCHAR2(20) NOT NULL, /* 출판사 */
   DATETIME DATE NOT NULL, /* 출판날짜 */
   ISBN VARCHAR2(50) NOT NULL, /* ISBN */
   CONTENTS VARCHAR2(2000) NOT NULL, /* 도서소개 */
   PRICE NUMBER, /* 판매가 */
   DELFLAG CHAR(1) NOT NULL /* DELFLAG */
);

ALTER TABLE BOOK
   ADD
      CONSTRAINT PK_BOOK
      PRIMARY KEY (
         BOOK_SEQ
      );

/* 도서대출정보 */
CREATE TABLE BOOK_DETAIL (
   DETAIL_SEQ VARCHAR2(20) NOT NULL, /* 식별번호 */
   BOOK_SEQ NUMBER NOT NULL, /* 도서번호 */
   LOAN_SEQ NUMBER NOT NULL, /* 대출번호 */
   RESERVE CHAR(1) NOT NULL, /* 현재 대출상태 */
   RESERVE_SEQ NUMBER, /* 예약번호 */
   DAMAGE_SEQ NUMBER /* 훼손코드 */
);

ALTER TABLE BOOK_DETAIL
   ADD
      CONSTRAINT PK_BOOK_DETAIL
      PRIMARY KEY (
         DETAIL_SEQ,
         BOOK_SEQ,
         LOAN_SEQ
      );

/* 게시판 */
CREATE TABLE BOOK_BOARD (
   BOARD_SEQ NUMBER NOT NULL, /* 게시판번호 */
   BOARD_TYPE VARCHAR2(20) NOT NULL, /* 게시판분류 */
   ID VARCHAR2(30) NOT NULL, /* 작성자ID */
   TITLE VARCHAR2(100) NOT NULL, /* 제목 */
   CONTENT VARCHAR2(2000) NOT NULL, /* 내용 */
   DELFLAG CHAR(1) NOT NULL, /* DELFLAG */
   REGDATE DATE NOT NULL /* 작성일자 */
);

ALTER TABLE BOOK_BOARD
   ADD
      CONSTRAINT PK_BOOK_BOARD
      PRIMARY KEY (
         BOARD_SEQ
      );

/* 댓글 */
CREATE TABLE BOOK_COMMENT (
   COMMENT_SEQ NUMBER NOT NULL, /* 댓글번호 */
   BOARD_SEQ NUMBER NOT NULL, /* 게시판번호 */
   ID VARCHAR2(30) NOT NULL, /* 작성자ID */
   CONTENT VARCHAR2(1000) NOT NULL, /* 내용 */
   DELFLAG CHAR(1) NOT NULL, /* DELFLAG */
   REGDATE DATE NOT NULL /* 작성일자 */
);

ALTER TABLE BOOK_COMMENT
   ADD
      CONSTRAINT PK_BOOK_COMMENT
      PRIMARY KEY (
         COMMENT_SEQ,
         BOARD_SEQ
      );

/* ban목록 */
CREATE TABLE BOOK_BANLIST (
   BANLIST_SEQ NUMBER NOT NULL, /* 리스트번호 */
   DECLARE_SEQ NUMBER NOT NULL, /* 신고번호 */
   BAN_REASON VARCHAR2(50) NOT NULL, /* 정지사유 */
   BAN_PERIOD NUMBER NOT NULL, /* 정지기간 */
   BAN_STATE CHAR(1) NOT NULL /* 현재상태 */
);

ALTER TABLE BOOK_BANLIST
   ADD
      CONSTRAINT PK_BOOK_BANLIST
      PRIMARY KEY (
         BANLIST_SEQ
      );

/* 대출 */
CREATE TABLE BOOK_LOAN (
   LOAN_SEQ NUMBER NOT NULL, /* 대출번호 */
   LOAN_SDAY DATE NOT NULL, /* 대출시작일 */
   LOAN_EDAY DATE NOT NULL, /* 반납일 */
   LOAN_CHECK CHAR(1) NOT NULL, /* 반납여부 */
   MEMBER_SEQ NUMBER NOT NULL /* 회원번호 */
);

ALTER TABLE BOOK_LOAN
   ADD
      CONSTRAINT PK_BOOK_LOAN
      PRIMARY KEY (
         LOAN_SEQ
      );

/* 회원신고 */
CREATE TABLE MEMBER_DECLARE (
   DECLARE_SEQ NUMBER NOT NULL, /* 신고번호 */
   MEMBER_SEQ NUMBER NOT NULL, /* 신고받은회원 */
   REPORT_ID VARCHAR2(30) NOT NULL, /* 신고자ID */
   DECLARE_DAY NUMBER NOT NULL, /* 신고일자 */
   DECLARE_REASON VARCHAR2(1000) NOT NULL /* 신고사유 */
);

ALTER TABLE MEMBER_DECLARE
   ADD
      CONSTRAINT PK_MEMBER_DECLARE
      PRIMARY KEY (
         DECLARE_SEQ
      );

/* 도서훼손정보 */
CREATE TABLE BOOK_DAMAGE_DETAIL (
   DAMAGE_SEQ NUMBER NOT NULL, /* 훼손코드 */
   KIND_DAMAGE VARCHAR2(50) NOT NULL, /* 훼손종류 */
   DAMAGE_CONTENT VARCHAR2(1000) NOT NULL /* 훼손내용 */
);

ALTER TABLE BOOK_DAMAGE_DETAIL
   ADD
      CONSTRAINT PK_BOOK_DAMAGE_DETAIL
      PRIMARY KEY (
         DAMAGE_SEQ
      );

/* 도서예약정보 */
CREATE TABLE BOOK_RESERVATION (
   RESERVE_SEQ NUMBER NOT NULL, /* 예약번호 */
   RESERVE_DATE DATE NOT NULL, /* 예약일 */
   RESERVE_PERIOD NUMBER NOT NULL /* 예약기간 */
);

ALTER TABLE BOOK_RESERVATION
   ADD
      CONSTRAINT PK_BOOK_RESERVATION
      PRIMARY KEY (
         RESERVE_SEQ
      );

ALTER TABLE BOOK_DETAIL
   ADD
      CONSTRAINT FK_BOOK_TO_BOOK_DETAIL
      FOREIGN KEY (
         BOOK_SEQ
      )
      REFERENCES BOOK (
         BOOK_SEQ
      );

ALTER TABLE BOOK_DETAIL
   ADD
      CONSTRAINT FK_BOOK_LOAN_TO_BOOK_DETAIL
      FOREIGN KEY (
         LOAN_SEQ
      )
      REFERENCES BOOK_LOAN (
         LOAN_SEQ
      );

ALTER TABLE BOOK_DETAIL
   ADD
      CONSTRAINT FK_BOOK_RESERVATION
      FOREIGN KEY (
         RESERVE_SEQ
      )
      REFERENCES BOOK_RESERVATION (
         RESERVE_SEQ
      )

ALTER TABLE BOOK_DETAIL
   ADD
      CONSTRAINT FK_BOOK_DAMAGE_DETAIL
      FOREIGN KEY (
         DAMAGE_SEQ
      )
      REFERENCES BOOK_DAMAGE_DETAIL (
         DAMAGE_SEQ
      )
      
ALTER TABLE BOOK_BANLIST
   ADD
      CONSTRAINT FK_MEMBER_DECLARE_
      FOREIGN KEY (
         DECLARE_SEQ
      )
      REFERENCES MEMBER_DECLARE (
         DECLARE_SEQ
      )
      
ALTER TABLE MEMBER_DECLARE
   ADD
      CONSTRAINT FK_BOOK_MEMBER_
      FOREIGN KEY (
         MEMBER_SEQ
      )
      REFERENCES BOOK_MEMBER (
         MEMBER_SEQ
      )

CREATE SEQUENCE BOOK_SEQ;      

/* 책 등록 */
SELECT *
	FROM BOOK b ;

INSERT INTO BOOK
(BOOK_SEQ, THUMBNAIL, TITLE, AUTHORS, PUBLISHER, DATETIME, ISBN, CONTENTS, PRICE, DELFLAG)
VALUES(BOOK_SEQ, '', '', '', '', '', '', '', 0, '');


	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
      